# Creating Naip and Sentinel Data from existing tif files 

In [40]:
import numpy as np
import tifffile as tiff
import scipy
from scipy import ndimage
import os

image_size = 200
image_size_s = int(image_size/10)

#origin_path = os.getcwd()
origin_path = '/Users/Simona'
os.chdir(origin_path)

sentinel = tiff.imread('Sentinel_31_05_1.tif')
sentinel_reshaped = sentinel.reshape(669,669,3)
naip = tiff.imread('NAIPFresno.tif')

#for i in range(0,5):
for i in range(0,int(naip.shape[0]/image_size)):
    naip_crop = naip[i*image_size:image_size+i*image_size,i*image_size:image_size+i*image_size,:]
    sentinel_crop = sentinel_reshaped[i*image_size_s:image_size_s+i*image_size_s,i*image_size_s:image_size_s+i*image_size_s,:]
    sentinel_resized = scipy.ndimage.zoom(sentinel_crop,(10,10,1), order=0)
    temp_path = "NAIPSentinel_200m_uint8_"+str(i)
    os.makedirs(origin_path+"/"+temp_path) 
    os.chdir(origin_path+"/"+temp_path)
    tiff.imsave('naip_'+str(i)+'.png',naip_crop)
    diff = np.amax(sentinel_resized)-np.amin(sentinel_resized)
    print(diff)
    sentinel_resized_rescaled = (sentinel_resized-np.amin(sentinel_resized))*1/diff*255
    sentinel_resized_uint8 = sentinel_resized_rescaled.astype(np.uint8)
    #print(sentinel_resized_uint8)
    print("max",np.amax(sentinel_resized_uint8))
    print("min",np.amin(sentinel_resized_uint8))
    print(sentinel_resized_uint8)
    tiff.imsave('sentinel_'+str(i)+'.png',sentinel_resized_uint8)

0.1231
max 255
min 0
[[[215 201 174]
  [215 201 174]
  [215 201 174]
  ...
  [ 10  65  71]
  [ 10  65  71]
  [ 10  65  71]]

 [[215 201 174]
  [215 201 174]
  [215 201 174]
  ...
  [ 10  65  71]
  [ 10  65  71]
  [ 10  65  71]]

 [[215 201 174]
  [215 201 174]
  [215 201 174]
  ...
  [ 10  65  71]
  [ 10  65  71]
  [ 10  65  71]]

 ...

 [[203 189 156]
  [203 189 156]
  [203 189 156]
  ...
  [ 11  65  73]
  [ 11  65  73]
  [ 11  65  73]]

 [[203 189 156]
  [203 189 156]
  [203 189 156]
  ...
  [ 11  65  73]
  [ 11  65  73]
  [ 11  65  73]]

 [[203 189 156]
  [203 189 156]
  [203 189 156]
  ...
  [ 11  65  73]
  [ 11  65  73]
  [ 11  65  73]]]
0.1099
max 255
min 0
[[[ 11  83  90]
  [ 11  83  90]
  [ 11  83  90]
  ...
  [ 63 102 108]
  [ 63 102 108]
  [ 63 102 108]]

 [[ 11  83  90]
  [ 11  83  90]
  [ 11  83  90]
  ...
  [ 63 102 108]
  [ 63 102 108]
  [ 63 102 108]]

 [[ 11  83  90]
  [ 11  83  90]
  [ 11  83  90]
  ...
  [ 63 102 108]
  [ 63 102 108]
  [ 63 102 108]]

 ...

 [[ 96 142

max 255
min 0
[[[ 91 103 119]
  [ 91 103 119]
  [ 91 103 119]
  ...
  [255 182 170]
  [255 182 170]
  [255 182 170]]

 [[ 91 103 119]
  [ 91 103 119]
  [ 91 103 119]
  ...
  [255 182 170]
  [255 182 170]
  [255 182 170]]

 [[ 91 103 119]
  [ 91 103 119]
  [ 91 103 119]
  ...
  [255 182 170]
  [255 182 170]
  [255 182 170]]

 ...

 [[  8  60  76]
  [  8  60  76]
  [  8  60  76]
  ...
  [146 132 133]
  [146 132 133]
  [146 132 133]]

 [[  8  60  76]
  [  8  60  76]
  [  8  60  76]
  ...
  [146 132 133]
  [146 132 133]
  [146 132 133]]

 [[  8  60  76]
  [  8  60  76]
  [  8  60  76]
  ...
  [146 132 133]
  [146 132 133]
  [146 132 133]]]
0.08180001
max 255
min 0
[[[143 147 115]
  [143 147 115]
  [143 147 115]
  ...
  [ 37  58  53]
  [ 37  58  53]
  [ 37  58  53]]

 [[143 147 115]
  [143 147 115]
  [143 147 115]
  ...
  [ 37  58  53]
  [ 37  58  53]
  [ 37  58  53]]

 [[143 147 115]
  [143 147 115]
  [143 147 115]
  ...
  [ 37  58  53]
  [ 37  58  53]
  [ 37  58  53]]

 ...

 [[255 202 16

In [15]:
sentinel_resized_uint8

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)